# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.PositiveIntegerField(default=0)),
                ('message', models.TextField()),
                ('traceback', models.TextField(blank=True, default=None, null=True)),
                ('filename', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('funcName', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('created', models.DateTimeField()),
                ('formatted', models.TextField()),
            ],
            options={
                'get_latest_by': 'created',
                'ordering': ['created'],
            },
        ),
    ]
